PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Models/ErrorViewModel.cs
namespace MiPrimeraAPPAspNetCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MiPrimeraAPPAspNetCore.Models;

namespace MiPrimeraAPPAspNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Controllers/LaboratorioController.cs
using CapaDatos;
using CapaEntidad;
using CapaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAPPAspNetCore.Controllers
{
    public class LaboratorioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<LaboratorioCLS> ListarLaboratorios()
        {
            LaboratorioDAL laboratorioDAL = new LaboratorioDAL();
            return laboratorioDAL.listarLaboratorios();
        }


        public List<LaboratorioCLS> filtrarLaboratorios(LaboratorioCLS objLaboratorio)
        {
            if (objLaboratorio == null)
            {
                objLaboratorio = new LaboratorioCLS();
            }
            LaboratorioBL obj = new LaboratorioBL();
            return obj.filtrarLaboratorio(objLaboratorio);
        }
    }
}

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Controllers/MedicamentoController.cs
using CapaDatos;
using CapaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAPPAspNetCore.Controllers
{
    public class MedicamentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public string Saludar()
        {
            return "Hola crack ";
        }

        public List<TipoMedicamentoCLS> ListartipoMedicamento()
        {
            TipoMedicamentoDAL tipoMedicamentoDAL = new TipoMedicamentoDAL();
            return tipoMedicamentoDAL.listarTipoMedicamento();
        }

    }
}

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Controllers/SucursalController.cs
using CapaDatos;
using CapaEntidad;
using CapaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAPPAspNetCore.Controllers
{
    public class SucursalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<SucursalCLS> ListarSucursales()
        {
            SucursalDAL sucursalDAL = new SucursalDAL();
            return sucursalDAL.listarSucursales();
        }


        public List<SucursalCLS> filtrarSucursales(SucursalCLS objSucursal)
        {
            if (objSucursal == null)
            {
                objSucursal = new SucursalCLS();
            }
            SucursalBL obj = new SucursalBL();
            return obj.filtrarSucursal(objSucursal);
        }
    }
}

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Controllers/TipoMedicamentoController.cs
using CapaDatos;
using CapaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAPPAspNetCore.Controllers
{
    public class TipoMedicamentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SinMenu()
        {
            return View();
        }


        public string saludar(string name)
        {
            return "Hello " + name;
        }

        public List<TipoMedicamentoCLS> ListartipoMedicamento()
        {
            TipoMedicamentoDAL tipoMedicamentoDAL = new TipoMedicamentoDAL();
            return tipoMedicamentoDAL.listarTipoMedicamento();
        }

        public List<TipoMedicamentoCLS> FiltrartipoMedicamento(string nombre)
        {
            TipoMedicamentoDAL tipoMedicamentoDAL = new TipoMedicamentoDAL();
            return tipoMedicamentoDAL.filtrarTipoMedicamento(nombre);
        }
    }
}

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Views/Laboratorio/Index.cshtml
@{
	ViewData["Title"] = "Laboratorio";
}

<h1>Laboratorio</h1>

<fieldset class="border p-3">
    <legend class="h5">Buscar Laboratorio</legend>
    <form id="frmBusqueda" method="post" class="row g-3">
        <div class="col-md-3">
            <label for="inputNombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="inputNombre">
        </div>
        <div class="col-md-3">
            <label for="inputDireccion" class="form-label">Dirección</label>
            <input type="text" class="form-control" name="direccion" id="inputDireccion">
        </div>
        <div class="col-md-3">
            <label for="inputDireccion" class="form-label">Persona Contacto</label>
            <input type="text" class="form-control" name="personaContacto" id="inputContacto">
        </div>
        <div class="col-12">
            <button type="button" class="btn btn-outline-danger" onclick="BuscarLaboratorio()">Buscar</button>
            <button type="button" class="btn btn-outline-success" onclick="LimpiarLaboratorio()">Limpiar</button>
        </div>
    </form>
</fieldset>


<div id="divTabla"></div>

<script src="~/js/generic.js"></script>
<script src="~/js/laboratorio.js"></script>

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Views/Medicamento/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Medicamento</h1>

<script src="~/js/generic.js"></script>
<script src="~/js/medicamento.js"></script>

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiPrimeraAPPAspNetCore</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MiPrimeraAPPAspNetCore.styles.css" asp-append-version="true" />
	<link href="~/font-awesome/css/all.css" rel="stylesheet" />
	<link href="~/font-awesome/css/all.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js" integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MiPrimeraAPPAspNetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoMedicamento" >TipoMedicamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sucursal">Sucursal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Laboratorio">Laboratorio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
	<input type="hidden" id="hdfOculto" value="@Url.Content("~")" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MiPrimeraAPPAspNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Views/Sucursal/Index.cshtml
@{
	ViewData["Title"] = "Sucursal";
}

<h1>Sucursal</h1>


<fieldset class="border p-4">
    <legend class="h5">Buscar Sucursal</legend>
    <form id="frmBusqueda" method="post" class="row g-3">
        <div class="col-md-4">
            <label for="inputNombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="inputNombre">
        </div>
        <div class="col-12">
            <button type="button" class="btn btn-outline-danger" onclick="BuscarSucursal()">Buscar</button>
            <button type="button" class="btn btn-outline-success" onclick="LimpiarSucursal()">Limpiar</button>
        </div>
    </form>
</fieldset>

<div id="divTabla"></div>

<script src="~/js/generic.js"></script>
<script src="~/js/sucursal.js"></script>

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Views/TipoMedicamento/Index.cshtml
@{
	ViewData["Title"] = "Index"; 
}

<h1>Tipo Medicamento</h1>


<div class="input-group">
	<input id="txtNombreTipoMedicamento" onkeyup="filtrarTipoMedicamento()" type="text" class="form-control"  placeholder="Ingresar tipo medicamento a buscar">
@* 	<button class="btn btn-outline-secondary" type="button" onclick="Buscar()">Buscar</button>
	<button class="btn btn-outline-secondary" type="button" onclick="Limpiar()">Limpiar</button> *@
</div>

<!-- Contenedor de la Tabla -->
    <br />
<div class="card shadow-lg">
    <div class="card-header bg-primary text-white">
        <h5 class="mb-0">Lista de Medicamentos</h5>
    </div>
    <div class="card-body">

        <div id="divTabla"></div> <!-- Aquí se cargará la tabla -->
    </div>
</div>

<script src="~/js/generic.js"></script>
<script src="~/js/tipomedicamento.js"></script>

PARCIAL 3/MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Views/TipoMedicamento/SinMenu.cshtml
@{
	ViewData["Title"] = "SinMenu";
}

<h1>Tipo Medicamento</h1>


<div id="divTabla">
</div>

<script src="~/js/tipomedicamento.js"></script>